// frontend/src/pages/Profile.jsx
import { useState, useEffect } from 'react';
import { getCurrentUser, changePassword } from '../utils/api';
import { useNotification } from '../contexts/NotificationContext';
import Navigation from '../components/shared/Navigation';
import Loading from '../components/shared/Loading';

export const Profile = () => {
  const { showSuccess, handleError } = useNotification();
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);
  const [showPasswordModal, setShowPasswordModal] = useState(false);
  const [passwordLoading, setPasswordLoading] = useState(false);
  const [passwordData, setPasswordData] = useState({
    currentPassword: '',
    newPassword: '',
    confirmPassword: ''
  });
  const [passwordErrors, setPasswordErrors] = useState({});

  useEffect(() => {
    loadUserProfile();
  }, []);

  const loadUserProfile = async () => {
    try {
      setLoading(true);
      const response = await getCurrentUser();
      setUser(response.data?.user || null);
    } catch (error) {
      handleError(error, 'Failed to load profile');
    } finally {
      setLoading(false);
    }
  };

  const formatDate = (date) => {
    return new Date(date).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const handlePasswordClick = () => {
    setPasswordData({
      currentPassword: '',
      newPassword: '',
      confirmPassword: ''
    });
    setPasswordErrors({});
    setShowPasswordModal(true);
  };

  const handlePasswordInputChange = (e) => {
    const { name, value } = e.target;
    setPasswordData(prev => ({
      ...prev,
      [name]: value
    }));
    // Clear error for this field
    if (passwordErrors[name]) {
      setPasswordErrors(prev => ({
        ...prev,
        [name]: ''
      }));
    }
  };

  const validatePasswordForm = () => {
    const errors = {};

    if (!passwordData.currentPassword) {
      errors.currentPassword = 'Current password is required';
    }

    if (!passwordData.newPassword) {
      errors.newPassword = 'New password is required';
    } else if (passwordData.newPassword.length < 6) {
      errors.newPassword = 'Password must be at least 6 characters';
    }

    if (!passwordData.confirmPassword) {
      errors.confirmPassword = 'Please confirm your password';
    } else if (passwordData.newPassword !== passwordData.confirmPassword) {
      errors.confirmPassword = 'Passwords do not match';
    }

    if (passwordData.currentPassword && passwordData.newPassword && 
        passwordData.currentPassword === passwordData.newPassword) {
      errors.newPassword = 'New password must be different from current password';
    }

    setPasswordErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const handleChangePassword = async (e) => {
    e.preventDefault();

    if (!validatePasswordForm()) {
      return;
    }

    try {
      setPasswordLoading(true);
      await changePassword(passwordData.currentPassword, passwordData.newPassword);
      showSuccess('Password Changed', 'Your password has been successfully updated');
      setShowPasswordModal(false);
      setPasswordData({
        currentPassword: '',
        newPassword: '',
        confirmPassword: ''
      });
      setPasswordErrors({});
    } catch (error) {
      handleError(error, 'Failed to change password');
    } finally {
      setPasswordLoading(false);
    }
  };

  const handleCancelPasswordChange = () => {
    setShowPasswordModal(false);
    setPasswordData({
      currentPassword: '',
      newPassword: '',
      confirmPassword: ''
    });
    setPasswordErrors({});
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-blue-50 to-indigo-50">
      <Navigation />
      
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <h1 className="text-4xl font-bold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent mb-2">
            My Profile
          </h1>
          <p className="text-gray-600">
            View and manage your account information
          </p>
        </div>

        {loading ? (
          <div className="bg-white rounded-xl shadow-lg p-12">
            <Loading />
          </div>
        ) : user ? (
          <div className="space-y-6">
            {/* Profile Information Card */}
            <div className="bg-white rounded-xl shadow-lg overflow-hidden">
              <div className="bg-gradient-to-r from-purple-600 to-blue-600 px-6 py-8">
                <div className="flex items-center">
                  <div className="h-20 w-20 rounded-full bg-white flex items-center justify-center shadow-lg">
                    <span className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
                      {user.username?.charAt(0).toUpperCase()}
                    </span>
                  </div>
                  <div className="ml-6">
                    <h2 className="text-2xl font-bold text-white">{user.username}</h2>
                    <p className="text-blue-100">{user.email}</p>
                  </div>
                </div>
              </div>

              <div className="px-6 py-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {/* Username */}
                  <div>
                    <label className="block text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">
                      Username
                    </label>
                    <p className="text-sm font-medium text-gray-900">{user.username}</p>
                  </div>

                  {/* Email */}
                  <div>
                    <label className="block text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">
                      Email Address
                    </label>
                    <p className="text-sm font-medium text-gray-900">{user.email}</p>
                  </div>

                  {/* Role */}
                  <div>
                    <label className="block text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">
                      Role
                    </label>
                    <span
                      className={`inline-flex px-3 py-1 text-xs leading-5 font-semibold rounded-full ${
                        user.role === 'admin'
                          ? 'bg-purple-100 text-purple-800'
                          : 'bg-blue-100 text-blue-800'
                      }`}
                    >
                      {user.role}
                    </span>
                  </div>

                  {/* User ID */}
                  <div>
                    <label className="block text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">
                      User ID
                    </label>
                    <p className="text-sm font-mono text-gray-900 break-all">{user.id || user._id}</p>
                  </div>

                  {/* Created At */}
                  <div>
                    <label className="block text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">
                      Member Since
                    </label>
                    <p className="text-sm font-medium text-gray-900">
                      {formatDate(user.createdAt || user.created_at)}
                    </p>
                  </div>

                  {/* Last Updated */}
                  <div>
                    <label className="block text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">
                      Last Updated
                    </label>
                    <p className="text-sm font-medium text-gray-900">
                      {formatDate(user.updatedAt || user.updated_at)}
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Security Settings Card */}
            <div className="bg-white rounded-xl shadow-lg overflow-hidden">
              <div className="px-6 py-4 border-b border-gray-200">
                <h3 className="text-xl font-bold text-gray-900 flex items-center">
                  <span className="bg-purple-100 rounded-lg p-2 mr-3">
                    <svg className="w-5 h-5 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                    </svg>
                  </span>
                  Security Settings
                </h3>
                <p className="mt-1 text-sm text-gray-600 ml-11">
                  Manage your password and security preferences
                </p>
              </div>

              <div className="px-6 py-6">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="text-sm font-medium text-gray-900">Password</h4>
                    <p className="text-sm text-gray-500 mt-1">
                      Update your password to keep your account secure
                    </p>
                  </div>
                  <button
                    onClick={handlePasswordClick}
                    className="px-4 py-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white text-sm font-medium rounded-lg shadow-md hover:shadow-lg hover:from-purple-700 hover:to-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500 transition-all flex items-center gap-2"
                  >
                    <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" />
                    </svg>
                    Change Password
                  </button>
                </div>
              </div>
            </div>

            {/* Account Information Card */}
            <div className="bg-white rounded-xl shadow-lg overflow-hidden">
              <div className="px-6 py-4 border-b border-gray-200">
                <h3 className="text-xl font-bold text-gray-900 flex items-center">
                  <span className="bg-blue-100 rounded-lg p-2 mr-3">
                    <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  </span>
                  Account Information
                </h3>
              </div>

              <div className="px-6 py-6">
                <div className="bg-gradient-to-r from-blue-50 to-purple-50 border border-blue-200 rounded-lg p-4">
                  <div className="flex">
                    <div className="flex-shrink-0">
                      <svg className="h-5 w-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                    </div>
                    <div className="ml-3">
                      <h3 className="text-sm font-medium text-blue-900">
                        Account Status: Active
                      </h3>
                      <div className="mt-2 text-sm text-blue-800">
                        <p>Your account is in good standing. If you need to update your profile information, please contact an administrator.</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div className="bg-white rounded-xl shadow-lg p-12 text-center">
            <p className="text-gray-500">Unable to load profile information</p>
          </div>
        )}
      </div>

      {/* Change Password Modal */}
      {showPasswordModal && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50 flex items-center justify-center">
          <div className="relative mx-auto p-6 border w-full max-w-md shadow-xl rounded-xl bg-white">
            <div className="flex justify-between items-start mb-4">
              <h3 className="text-xl font-bold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
                Change Password
              </h3>
              <button
                onClick={handleCancelPasswordChange}
                className="text-gray-400 hover:text-gray-600 transition-colors"
                disabled={passwordLoading}
              >
                <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>

            <form onSubmit={handleChangePassword}>
              <div className="space-y-4">
                {/* Current Password */}
                <div>
                  <label htmlFor="currentPassword" className="block text-sm font-medium text-gray-700 mb-1">
                    Current Password <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="password"
                    id="currentPassword"
                    name="currentPassword"
                    value={passwordData.currentPassword}
                    onChange={handlePasswordInputChange}
                    className={`w-full px-3 py-2 border rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-500 transition-colors ${
                      passwordErrors.currentPassword ? 'border-red-500' : 'border-gray-300'
                    }`}
                    placeholder="Enter current password"
                    disabled={passwordLoading}
                  />
                  {passwordErrors.currentPassword && (
                    <p className="mt-1 text-sm text-red-600">{passwordErrors.currentPassword}</p>
                  )}
                </div>

                {/* New Password */}
                <div>
                  <label htmlFor="newPassword" className="block text-sm font-medium text-gray-700 mb-1">
                    New Password <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="password"
                    id="newPassword"
                    name="newPassword"
                    value={passwordData.newPassword}
                    onChange={handlePasswordInputChange}
                    className={`w-full px-3 py-2 border rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-500 transition-colors ${
                      passwordErrors.newPassword ? 'border-red-500' : 'border-gray-300'
                    }`}
                    placeholder="Enter new password (min 6 characters)"
                    disabled={passwordLoading}
                  />
                  {passwordErrors.newPassword && (
                    <p className="mt-1 text-sm text-red-600">{passwordErrors.newPassword}</p>
                  )}
                </div>

                {/* Confirm Password */}
                <div>
                  <label htmlFor="confirmPassword" className="block text-sm font-medium text-gray-700 mb-1">
                    Confirm New Password <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="password"
                    id="confirmPassword"
                    name="confirmPassword"
                    value={passwordData.confirmPassword}
                    onChange={handlePasswordInputChange}
                    className={`w-full px-3 py-2 border rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-500 transition-colors ${
                      passwordErrors.confirmPassword ? 'border-red-500' : 'border-gray-300'
                    }`}
                    placeholder="Confirm new password"
                    disabled={passwordLoading}
                  />
                  {passwordErrors.confirmPassword && (
                    <p className="mt-1 text-sm text-red-600">{passwordErrors.confirmPassword}</p>
                  )}
                </div>

                {/* Password Requirements */}
                <div className="bg-gradient-to-r from-blue-50 to-purple-50 border border-blue-200 rounded-lg p-3">
                  <p className="text-xs font-medium text-blue-900 mb-1">Password Requirements:</p>
                  <ul className="text-xs text-blue-800 space-y-1">
                    <li>• At least 6 characters long</li>
                    <li>• Different from current password</li>
                    <li>• Both new password fields must match</li>
                  </ul>
                </div>
              </div>

              {/* Buttons */}
              <div className="mt-6 flex gap-3">
                <button
                  type="button"
                  onClick={handleCancelPasswordChange}
                  className="flex-1 px-4 py-2 bg-white border border-gray-300 text-gray-700 text-sm font-medium rounded-lg shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500 transition-colors"
                  disabled={passwordLoading}
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="flex-1 px-4 py-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white text-sm font-medium rounded-lg shadow-md hover:shadow-lg hover:from-purple-700 hover:to-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                  disabled={passwordLoading}
                >
                  {passwordLoading ? (
                    <>
                      <svg className="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      Changing...
                    </>
                  ) : (
                    'Change Password'
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default Profile;

// frontend/src/app/profile/profile.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { Subscription } from 'rxjs';
import { AuthService, User, UserProfileUpdate, PasswordChangeRequest } from '../shared/services/auth.service';
import { ErrorHandlerService } from '../shared/services/error-handler.service';
import { NavigationComponent } from '../shared/components/navigation/navigation.component';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule, NavigationComponent],
  template: `
    <div class="min-h-screen bg-gray-50">
      <app-navigation></app-navigation>

      <main class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
        <div class="px-4 py-6 sm:px-0">
          <!-- Header -->
          <div class="mb-8">
            <h1 class="text-3xl font-bold text-gray-900">Profile Settings</h1>
            <p class="mt-1 text-sm text-gray-600">
              Manage your account information and preferences
            </p>
          </div>

          <div class="grid grid-cols-1 gap-6 lg:grid-cols-3">
            <!-- Profile Information -->
            <div class="lg:col-span-2">
              <div class="bg-white shadow rounded-lg">
                <div class="px-4 py-5 sm:p-6">
                  <h3 class="text-lg leading-6 font-medium text-gray-900 mb-4">
                    Profile Information
                  </h3>
                  
                  <form [formGroup]="profileForm" (ngSubmit)="updateProfile()">
                    <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
                      <!-- Email -->
                      <div class="sm:col-span-2">
                        <label for="email" class="block text-sm font-medium text-gray-700">
                          Email address
                        </label>
                        <div class="mt-1">
                          <input
                            type="email"
                            id="email"
                            formControlName="email"
                            class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
                            [class.border-red-300]="profileForm.get('email')?.invalid && profileForm.get('email')?.touched"
                          />
                          <div *ngIf="profileForm.get('email')?.invalid && profileForm.get('email')?.touched" 
                               class="mt-1 text-sm text-red-600">
                            <div *ngIf="profileForm.get('email')?.errors?.['required']">Email is required</div>
                            <div *ngIf="profileForm.get('email')?.errors?.['email']">Please enter a valid email</div>
                          </div>
                        </div>
                      </div>

                      <!-- First Name -->
                      <div>
                        <label for="firstName" class="block text-sm font-medium text-gray-700">
                          First name
                        </label>
                        <div class="mt-1">
                          <input
                            type="text"
                            id="firstName"
                            formControlName="first_name"
                            class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
                            [class.border-red-300]="profileForm.get('first_name')?.invalid && profileForm.get('first_name')?.touched"
                          />
                          <div *ngIf="profileForm.get('first_name')?.invalid && profileForm.get('first_name')?.touched" 
                               class="mt-1 text-sm text-red-600">
                            <div *ngIf="profileForm.get('first_name')?.errors?.['minlength']">First name must be at least 1 character</div>
                            <div *ngIf="profileForm.get('first_name')?.errors?.['maxlength']">First name cannot exceed 50 characters</div>
                          </div>
                        </div>
                      </div>

                      <!-- Last Name -->
                      <div>
                        <label for="lastName" class="block text-sm font-medium text-gray-700">
                          Last name
                        </label>
                        <div class="mt-1">
                          <input
                            type="text"
                            id="lastName"
                            formControlName="last_name"
                            class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
                            [class.border-red-300]="profileForm.get('last_name')?.invalid && profileForm.get('last_name')?.touched"
                          />
                          <div *ngIf="profileForm.get('last_name')?.invalid && profileForm.get('last_name')?.touched" 
                               class="mt-1 text-sm text-red-600">
                            <div *ngIf="profileForm.get('last_name')?.errors?.['minlength']">Last name must be at least 1 character</div>
                            <div *ngIf="profileForm.get('last_name')?.errors?.['maxlength']">Last name cannot exceed 50 characters</div>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div class="mt-6">
                      <button
                        type="submit"
                        [disabled]="profileForm.invalid || isUpdatingProfile"
                        class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
                      >
                        <span *ngIf="isUpdatingProfile" class="mr-2">
                          <svg class="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
                            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                          </svg>
                        </span>
                        {{ isUpdatingProfile ? 'Updating...' : 'Update Profile' }}
                      </button>
                    </div>
                  </form>
                </div>
              </div>

              <!-- Change Password -->
              <div class="bg-white shadow rounded-lg mt-6">
                <div class="px-4 py-5 sm:p-6">
                  <h3 class="text-lg leading-6 font-medium text-gray-900 mb-4">
                    Change Password
                  </h3>
                  
                  <form [formGroup]="passwordForm" (ngSubmit)="changePassword()">
                    <div class="space-y-6">
                      <!-- Current Password -->
                      <div>
                        <label for="currentPassword" class="block text-sm font-medium text-gray-700">
                          Current password
                        </label>
                        <div class="mt-1">
                          <input
                            type="password"
                            id="currentPassword"
                            formControlName="current_password"
                            class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
                            [class.border-red-300]="passwordForm.get('current_password')?.invalid && passwordForm.get('current_password')?.touched"
                          />
                          <div *ngIf="passwordForm.get('current_password')?.invalid && passwordForm.get('current_password')?.touched" 
                               class="mt-1 text-sm text-red-600">
                            <div *ngIf="passwordForm.get('current_password')?.errors?.['required']">Current password is required</div>
                          </div>
                        </div>
                      </div>

                      <!-- New Password -->
                      <div>
                        <label for="newPassword" class="block text-sm font-medium text-gray-700">
                          New password
                        </label>
                        <div class="mt-1">
                          <input
                            type="password"
                            id="newPassword"
                            formControlName="new_password"
                            class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
                            [class.border-red-300]="passwordForm.get('new_password')?.invalid && passwordForm.get('new_password')?.touched"
                          />
                          <div *ngIf="passwordForm.get('new_password')?.invalid && passwordForm.get('new_password')?.touched" 
                               class="mt-1 text-sm text-red-600">
                            <div *ngIf="passwordForm.get('new_password')?.errors?.['required']">New password is required</div>
                            <div *ngIf="passwordForm.get('new_password')?.errors?.['minlength']">Password must be at least 6 characters</div>
                          </div>
                        </div>
                      </div>

                      <!-- Confirm Password -->
                      <div>
                        <label for="confirmPassword" class="block text-sm font-medium text-gray-700">
                          Confirm new password
                        </label>
                        <div class="mt-1">
                          <input
                            type="password"
                            id="confirmPassword"
                            formControlName="confirm_password"
                            class="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
                            [class.border-red-300]="passwordForm.get('confirm_password')?.invalid && passwordForm.get('confirm_password')?.touched"
                          />
                          <div *ngIf="passwordForm.get('confirm_password')?.invalid && passwordForm.get('confirm_password')?.touched" 
                               class="mt-1 text-sm text-red-600">
                            <div *ngIf="passwordForm.get('confirm_password')?.errors?.['required']">Please confirm your password</div>
                            <div *ngIf="passwordForm.get('confirm_password')?.errors?.['passwordMismatch']">Passwords do not match</div>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div class="mt-6">
                      <button
                        type="submit"
                        [disabled]="passwordForm.invalid || isChangingPassword"
                        class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 disabled:opacity-50 disabled:cursor-not-allowed"
                      >
                        <span *ngIf="isChangingPassword" class="mr-2">
                          <svg class="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
                            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                          </svg>
                        </span>
                        {{ isChangingPassword ? 'Changing...' : 'Change Password' }}
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </div>

            <!-- Account Information Sidebar -->
            <div class="lg:col-span-1">
              <div class="bg-white shadow rounded-lg">
                <div class="px-4 py-5 sm:p-6">
                  <h3 class="text-lg leading-6 font-medium text-gray-900 mb-4">
                    Account Information
                  </h3>
                  
                  <dl class="space-y-4">
                    <div>
                      <dt class="text-sm font-medium text-gray-500">Account Status</dt>
                      <dd class="mt-1">
                        <span [ngClass]="currentUser?.is_active ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'" 
                              class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium">
                          {{ currentUser?.is_active ? 'Active' : 'Inactive' }}
                        </span>
                      </dd>
                    </div>

                    <div>
                      <dt class="text-sm font-medium text-gray-500">Email Verification</dt>
                      <dd class="mt-1">
                        <span [ngClass]="currentUser?.is_verified ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'" 
                              class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium">
                          {{ currentUser?.is_verified ? 'Verified' : 'Unverified' }}
                        </span>
                      </dd>
                    </div>


                    <div>
                      <dt class="text-sm font-medium text-gray-500">Member Since</dt>
                      <dd class="mt-1 text-sm text-gray-900">{{ currentUser?.created_at | date:'longDate' }}</dd>
                    </div>



                  </dl>
                </div>
              </div>

              <!-- Quick Actions -->
              <div class="bg-white shadow rounded-lg mt-6">
                <div class="px-4 py-5 sm:p-6">
                  <h3 class="text-lg leading-6 font-medium text-gray-900 mb-4">
                    Quick Actions
                  </h3>
                  
                  <div class="space-y-3">
                    <button
                      type="button"
                      routerLink="/dashboard"
                      class="w-full inline-flex justify-center items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                    >
                      <svg class="-ml-1 mr-2 h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2H5a2 2 0 00-2-2z" />
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 5a2 2 0 012-2h4a2 2 0 012 2v2H8V5z" />
                      </svg>
                      Go to Dashboard
                    </button>

                    <button
                      type="button"
                      routerLink="/manuscripts"
                      class="w-full inline-flex justify-center items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                    >
                      <svg class="-ml-1 mr-2 h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                      </svg>
                      View Manuscripts
                    </button>

                    <button
                      type="button"
                      (click)="refreshProfile()"
                      [disabled]="isRefreshing"
                      class="w-full inline-flex justify-center items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
                    >
                      <svg class="-ml-1 mr-2 h-4 w-4" [class.animate-spin]="isRefreshing" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                      </svg>
                      {{ isRefreshing ? 'Refreshing...' : 'Refresh Profile' }}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  `
})
export class ProfileComponent implements OnInit, OnDestroy {
  currentUser: User | null = null;
  profileForm: FormGroup;
  passwordForm: FormGroup;
  
  isUpdatingProfile = false;
  isChangingPassword = false;
  isRefreshing = false;
  
  private subscription?: Subscription;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private errorHandler: ErrorHandlerService
  ) {
    this.profileForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      first_name: ['', [Validators.minLength(1), Validators.maxLength(50)]],
      last_name: ['', [Validators.minLength(1), Validators.maxLength(50)]]
    });

    this.passwordForm = this.fb.group({
      current_password: ['', [Validators.required]],
      new_password: ['', [Validators.required, Validators.minLength(6)]],
      confirm_password: ['', [Validators.required]]
    }, { validators: this.passwordMatchValidator });
  }

  ngOnInit(): void {
    this.subscription = this.authService.currentUser$.subscribe(user => {
      this.currentUser = user;
      if (user) {
        this.profileForm.patchValue({
          email: user.email,
          first_name: user.first_name || '',
          last_name: user.last_name || ''
        });
      }
    });

    // Load fresh profile data
    this.refreshProfile();
  }

  ngOnDestroy(): void {
    if (this.subscription) {
      this.subscription.unsubscribe();
    }
  }

  passwordMatchValidator(form: FormGroup) {
    const newPassword = form.get('new_password');
    const confirmPassword = form.get('confirm_password');
    
    if (newPassword && confirmPassword && newPassword.value !== confirmPassword.value) {
      confirmPassword.setErrors({ passwordMismatch: true });
    } else if (confirmPassword?.errors?.['passwordMismatch']) {
      delete confirmPassword.errors['passwordMismatch'];
      if (Object.keys(confirmPassword.errors).length === 0) {
        confirmPassword.setErrors(null);
      }
    }
    
    return null;
  }

  updateProfile(): void {
    if (this.profileForm.valid) {
      this.isUpdatingProfile = true;
      
      const profileData: UserProfileUpdate = this.profileForm.value;
      
      this.authService.updateProfile(profileData).subscribe({
        next: (user: User) => {
          this.errorHandler.showSuccess('Profile updated successfully');
          this.isUpdatingProfile = false;
        },
        error: (error: any) => {
          this.errorHandler.showError(error);
          this.isUpdatingProfile = false;
        }
      });
    }
  }

  changePassword(): void {
    if (this.passwordForm.valid) {
      this.isChangingPassword = true;
      
      const passwordData: PasswordChangeRequest = this.passwordForm.value;
      
      this.authService.changePassword(passwordData).subscribe({
        next: () => {
          this.errorHandler.showSuccess('Password changed successfully');
          this.passwordForm.reset();
          this.isChangingPassword = false;
        },
        error: (error: any) => {
          this.errorHandler.showError(error);
          this.isChangingPassword = false;
        }
      });
    }
  }

  refreshProfile(): void {
    this.isRefreshing = true;
    
    this.authService.getCurrentUserProfile().subscribe({
      next: (user: User) => {
        this.errorHandler.showSuccess('Profile refreshed');
        this.isRefreshing = false;
      },
      error: (error: any) => {
        this.errorHandler.showError(error);
        this.isRefreshing = false;
      }
    });
  }
}
