// frontend/src/app/admin/conversion-reports/conversion-reports.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { AdminService, ManuscriptReport, ConversionStatistics } from '../../shared/services/admin.service';
import { ErrorHandlerService } from '../../shared/services/error-handler.service';
import { NavigationComponent } from '../../shared/components/navigation/navigation.component';
import { LoadingComponent } from '../../shared/components/loading/loading.component';

@Component({
  selector: 'app-conversion-reports',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, NavigationComponent, LoadingComponent],
  template: `
    <div class="min-h-screen bg-gray-50">
      <app-navigation></app-navigation>

      <main class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
        <div class="px-4 py-6 sm:px-0">
          <!-- Header -->
          <div class="mb-8">
            <h1 class="text-3xl font-bold text-gray-900">Conversion Reports</h1>
            <p class="mt-1 text-sm text-gray-600">
              View and manage manuscript conversion jobs
            </p>
          </div>

          <!-- Statistics Cards -->
          <div *ngIf="statistics" class="mb-6 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-5">
            <div class="bg-white overflow-hidden shadow rounded-lg">
              <div class="p-5">
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                    <svg class="h-6 w-6 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                  </div>
                  <div class="ml-5 w-0 flex-1">
                    <dl>
                      <dt class="text-sm font-medium text-gray-500 truncate">Total</dt>
                      <dd class="text-lg font-medium text-gray-900">{{ statistics.total_manuscripts }}</dd>
                    </dl>
                  </div>
                </div>
              </div>
            </div>

            <div class="bg-yellow-50 overflow-hidden shadow rounded-lg">
              <div class="p-5">
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                    <svg class="h-6 w-6 text-yellow-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  </div>
                  <div class="ml-5 w-0 flex-1">
                    <dl>
                      <dt class="text-sm font-medium text-yellow-700 truncate">Processing</dt>
                      <dd class="text-lg font-medium text-yellow-900">{{ statistics.processing_count }}</dd>
                    </dl>
                  </div>
                </div>
              </div>
            </div>

            <div class="bg-green-50 overflow-hidden shadow rounded-lg">
              <div class="p-5">
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                    <svg class="h-6 w-6 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                    </svg>
                  </div>
                  <div class="ml-5 w-0 flex-1">
                    <dl>
                      <dt class="text-sm font-medium text-green-700 truncate">Completed</dt>
                      <dd class="text-lg font-medium text-green-900">{{ statistics.completed_count }}</dd>
                    </dl>
                  </div>
                </div>
              </div>
            </div>

            <div class="bg-red-50 overflow-hidden shadow rounded-lg">
              <div class="p-5">
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                    <svg class="h-6 w-6 text-red-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </div>
                  <div class="ml-5 w-0 flex-1">
                    <dl>
                      <dt class="text-sm font-medium text-red-700 truncate">Failed</dt>
                      <dd class="text-lg font-medium text-red-900">{{ statistics.failed_count }}</dd>
                    </dl>
                  </div>
                </div>
              </div>
            </div>

            <div class="bg-blue-50 overflow-hidden shadow rounded-lg">
              <div class="p-5">
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                    <svg class="h-6 w-6 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                    </svg>
                  </div>
                  <div class="ml-5 w-0 flex-1">
                    <dl>
                      <dt class="text-sm font-medium text-blue-700 truncate">Success Rate</dt>
                      <dd class="text-lg font-medium text-blue-900">{{ statistics.success_rate }}%</dd>
                    </dl>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Filters -->
          <div class="bg-white shadow rounded-lg p-6 mb-6">
            <h3 class="text-lg font-medium text-gray-900 mb-4">Filters</h3>
            <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
              <div>
                <label for="status" class="block text-sm font-medium text-gray-700 mb-1">Status</label>
                <select
                  id="status"
                  name="status"
                  [(ngModel)]="filters.status"
                  (change)="applyFilters()"
                  class="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md"
                >
                  <option value="">All Statuses</option>
                  <option value="pending">Pending</option>
                  <option value="processing">Processing</option>
                  <option value="complete">Complete</option>
                  <option value="failed">Failed</option>
                </select>
              </div>

              <div>
                <label for="inputFormat" class="block text-sm font-medium text-gray-700 mb-1">Input Format</label>
                <select
                  id="inputFormat"
                  name="inputFormat"
                  [(ngModel)]="filters.inputFormat"
                  (change)="applyFilters()"
                  class="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md"
                >
                  <option value="">All Formats</option>
                  <option value="pdf">PDF</option>
                  <option value="epub">EPUB</option>
                </select>
              </div>

              <div>
                <label for="isbn" class="block text-sm font-medium text-gray-700 mb-1">ISBN</label>
                <input
                  type="text"
                  id="isbn"
                  name="isbn"
                  [(ngModel)]="filters.isbn"
                  (keyup.enter)="applyFilters()"
                  placeholder="Search by ISBN"
                  class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                />
              </div>

              <div>
                <label for="search" class="block text-sm font-medium text-gray-700 mb-1">Search</label>
                <input
                  type="text"
                  id="search"
                  name="search"
                  [(ngModel)]="filters.search"
                  (keyup.enter)="applyFilters()"
                  placeholder="File name or ISBN"
                  class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                />
              </div>
            </div>

            <div class="mt-4 flex justify-end space-x-3">
              <button
                type="button"
                (click)="clearFilters()"
                class="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              >
                Clear Filters
              </button>
              <button
                type="button"
                (click)="applyFilters()"
                class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              >
                Apply Filters
              </button>
            </div>
          </div>

          <!-- Reports Table -->
          <div class="bg-white shadow rounded-lg overflow-hidden">
            <div class="px-4 py-5 sm:p-6">
              <div *ngIf="isLoading" class="flex justify-center py-12">
                <app-loading message="Loading conversion reports..." size="lg"></app-loading>
              </div>

              <div *ngIf="!isLoading && reports.length === 0" class="text-center py-12">
                <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                <h3 class="mt-2 text-sm font-medium text-gray-900">No conversion reports found</h3>
                <p class="mt-1 text-sm text-gray-500">Try adjusting your filters or check back later.</p>
              </div>

              <div *ngIf="!isLoading && reports.length > 0" class="overflow-x-auto">
                <table class="min-w-full divide-y divide-gray-200">
                  <thead class="bg-gray-50">
                    <tr>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">File Name</th>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">User</th>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Format</th>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">ISBN</th>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Upload Date</th>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                    </tr>
                  </thead>
                  <tbody class="bg-white divide-y divide-gray-200">
                    <tr *ngFor="let report of reports" class="hover:bg-gray-50">
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        {{ report.file_name }}
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {{ report.user_email || 'N/A' }}
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap">
                        <span [ngClass]="getStatusClass(report.status)" class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full">
                          {{ report.status }}
                        </span>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {{ report.input_format || 'N/A' }}
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {{ report.isbn || 'N/A' }}
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {{ report.upload_date | date:'short' }}
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium space-x-2">
                        <button
                          type="button"
                          (click)="viewDetails(report)"
                          class="text-indigo-600 hover:text-indigo-900"
                        >
                          View
                        </button>
                        <button
                          *ngIf="report.status === 'failed'"
                          type="button"
                          (click)="retryConversion(report.id)"
                          class="text-green-600 hover:text-green-900"
                        >
                          Retry
                        </button>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <!-- Pagination -->
              <div *ngIf="!isLoading && reports.length > 0" class="mt-4 flex items-center justify-between border-t border-gray-200 pt-4">
                <div class="flex-1 flex justify-between sm:hidden">
                  <button
                    (click)="previousPage()"
                    [disabled]="currentPage === 1"
                    class="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 disabled:opacity-50"
                  >
                    Previous
                  </button>
                  <button
                    (click)="nextPage()"
                    [disabled]="currentPage >= totalPages"
                    class="ml-3 relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 disabled:opacity-50"
                  >
                    Next
                  </button>
                </div>
                <div class="hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
                  <div>
                    <p class="text-sm text-gray-700">
                      Showing
                      <span class="font-medium">{{ (currentPage - 1) * pageSize + 1 }}</span>
                      to
                      <span class="font-medium">{{ Math.min(currentPage * pageSize, totalItems) }}</span>
                      of
                      <span class="font-medium">{{ totalItems }}</span>
                      results
                    </p>
                  </div>
                  <div>
                    <nav class="relative z-0 inline-flex rounded-md shadow-sm -space-x-px" aria-label="Pagination">
                      <button
                        (click)="previousPage()"
                        [disabled]="currentPage === 1"
                        class="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 disabled:opacity-50"
                      >
                        <span class="sr-only">Previous</span>
                        <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                          <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
                        </svg>
                      </button>
                      <span class="relative inline-flex items-center px-4 py-2 border border-gray-300 bg-white text-sm font-medium text-gray-700">
                        Page {{ currentPage }} of {{ totalPages }}
                      </span>
                      <button
                        (click)="nextPage()"
                        [disabled]="currentPage >= totalPages"
                        class="relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 disabled:opacity-50"
                      >
                        <span class="sr-only">Next</span>
                        <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                          <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                        </svg>
                      </button>
                    </nav>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <!-- Details Modal -->
      <div *ngIf="selectedReport" class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
        <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
          <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true" (click)="closeDetails()"></div>
          <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
          <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
            <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
              <div class="sm:flex sm:items-start">
                <div class="mt-3 text-center sm:mt-0 sm:text-left w-full">
                  <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title">
                    Conversion Details
                  </h3>
                  <div class="mt-4 space-y-3">
                    <div>
                      <p class="text-sm font-medium text-gray-500">File Name</p>
                      <p class="text-sm text-gray-900">{{ selectedReport.file_name }}</p>
                    </div>
                    <div>
                      <p class="text-sm font-medium text-gray-500">User</p>
                      <p class="text-sm text-gray-900">{{ selectedReport.user_email || 'N/A' }}</p>
                    </div>
                    <div>
                      <p class="text-sm font-medium text-gray-500">Status</p>
                      <span [ngClass]="getStatusClass(selectedReport.status)" class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full">
                        {{ selectedReport.status }}
                      </span>
                    </div>
                    <div>
                      <p class="text-sm font-medium text-gray-500">Input Format</p>
                      <p class="text-sm text-gray-900">{{ selectedReport.input_format || 'N/A' }}</p>
                    </div>
                    <div>
                      <p class="text-sm font-medium text-gray-500">ISBN</p>
                      <p class="text-sm text-gray-900">{{ selectedReport.isbn || 'N/A' }}</p>
                    </div>
                    <div>
                      <p class="text-sm font-medium text-gray-500">File Size</p>
                      <p class="text-sm text-gray-900">{{ formatFileSize(selectedReport.file_size) }}</p>
                    </div>
                    <div>
                      <p class="text-sm font-medium text-gray-500">Upload Date</p>
                      <p class="text-sm text-gray-900">{{ selectedReport.upload_date | date:'medium' }}</p>
                    </div>
                    <div *ngIf="selectedReport.processing_started_at">
                      <p class="text-sm font-medium text-gray-500">Processing Started</p>
                      <p class="text-sm text-gray-900">{{ selectedReport.processing_started_at | date:'medium' }}</p>
                    </div>
                    <div *ngIf="selectedReport.processing_completed_at">
                      <p class="text-sm font-medium text-gray-500">Processing Completed</p>
                      <p class="text-sm text-gray-900">{{ selectedReport.processing_completed_at | date:'medium' }}</p>
                    </div>
                    <div *ngIf="selectedReport.error_message">
                      <p class="text-sm font-medium text-red-500">Error Message</p>
                      <p class="text-sm text-red-700 bg-red-50 p-2 rounded">{{ selectedReport.error_message }}</p>
                    </div>
                    <div>
                      <p class="text-sm font-medium text-gray-500">Retry Count</p>
                      <p class="text-sm text-gray-900">{{ selectedReport.retry_count }}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
              <button
                type="button"
                (click)="closeDetails()"
                class="w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:ml-3 sm:w-auto sm:text-sm"
              >
                Close
              </button>
              <button
                *ngIf="selectedReport.status === 'failed'"
                type="button"
                (click)="retryConversion(selectedReport.id); closeDetails()"
                class="mt-3 w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-green-600 text-base font-medium text-white hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 sm:mt-0 sm:w-auto sm:text-sm"
              >
                Retry Conversion
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  `
})
export class ConversionReportsComponent implements OnInit {
  reports: ManuscriptReport[] = [];
  statistics: ConversionStatistics | null = null;
  selectedReport: ManuscriptReport | null = null;

  filters = {
    status: '',
    inputFormat: '',
    isbn: '',
    search: ''
  };

  currentPage = 1;
  pageSize = 20;
  totalItems = 0;
  totalPages = 0;

  isLoading = false;
  Math = Math;

  constructor(
    private adminService: AdminService,
    private errorHandler: ErrorHandlerService
  ) {}

  ngOnInit(): void {
    this.loadStatistics();
    this.loadReports();
  }

  loadStatistics(): void {
    this.adminService.getConversionStatistics().subscribe({
      next: (stats) => {
        this.statistics = stats;
      },
      error: (error) => {
        this.errorHandler.showError(error);
      }
    });
  }

  loadReports(): void {
    this.isLoading = true;
    const params = {
      page: this.currentPage,
      size: this.pageSize,
      ...this.filters
    };

    this.adminService.getManuscriptReports(params).subscribe({
      next: (response) => {
        this.reports = response.items;
        this.totalItems = response.total;
        this.totalPages = response.pages;
        this.isLoading = false;
      },
      error: (error) => {
        this.errorHandler.showError(error);
        this.isLoading = false;
      }
    });
  }

  applyFilters(): void {
    this.currentPage = 1;
    this.loadReports();
  }

  clearFilters(): void {
    this.filters = {
      status: '',
      inputFormat: '',
      isbn: '',
      search: ''
    };
    this.applyFilters();
  }

  previousPage(): void {
    if (this.currentPage > 1) {
      this.currentPage--;
      this.loadReports();
    }
  }

  nextPage(): void {
    if (this.currentPage < this.totalPages) {
      this.currentPage++;
      this.loadReports();
    }
  }

  viewDetails(report: ManuscriptReport): void {
    this.selectedReport = report;
  }

  closeDetails(): void {
    this.selectedReport = null;
  }

  retryConversion(manuscriptId: string): void {
    if (confirm('Are you sure you want to retry this conversion?')) {
      this.adminService.retryConversion(manuscriptId).subscribe({
        next: () => {
          this.errorHandler.showSuccess('Conversion queued for retry');
          this.loadReports();
          this.loadStatistics();
        },
        error: (error) => {
          this.errorHandler.showError(error);
        }
      });
    }
  }

  getStatusClass(status: string): string {
    switch (status) {
      case 'complete':
        return 'bg-green-100 text-green-800';
      case 'processing':
        return 'bg-yellow-100 text-yellow-800';
      case 'pending':
        return 'bg-blue-100 text-blue-800';
      case 'failed':
        return 'bg-red-100 text-red-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  }

  formatFileSize(bytes: number | null | undefined): string {
    if (!bytes) return 'N/A';
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(2) + ' KB';
    if (bytes < 1024 * 1024 * 1024) return (bytes / (1024 * 1024)).toFixed(2) + ' MB';
    return (bytes / (1024 * 1024 * 1024)).toFixed(2) + ' GB';
  }
}

// frontend/src/pages/admin/ConversionReports.jsx
import { useState, useEffect } from 'react';
import { getConversionRecords, getConversionStats } from '../../utils/api';
import { useNotification } from '../../contexts/NotificationContext';
import Loading from '../../components/shared/Loading';
import useExportReport from '../../hooks/useExportReport';
import * as XLSX from 'xlsx';

export const ConversionDashboard = () => {
  const { handleError, showSuccess } = useNotification();
  const { exportConversionReport } = useExportReport();
  const [records, setRecords] = useState([]);
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedFileType, setSelectedFileType] = useState('all');
  const [selectedStatus, setSelectedStatus] = useState('all');
  const [sortColumn, setSortColumn] = useState('createdAt');
  const [sortDirection, setSortDirection] = useState('desc');
  const [total, setTotal] = useState(0);

  useEffect(() => {
    loadData();
  }, []);

  useEffect(() => {
    // Debounce search
    const timer = setTimeout(() => {
      loadRecords();
    }, 300);
    return () => clearTimeout(timer);
  }, [searchTerm, selectedFileType, selectedStatus, sortColumn, sortDirection]);

  const loadData = async () => {
    setLoading(true);
    await Promise.all([loadRecords(), loadStats()]);
    setLoading(false);
  };

  const loadRecords = async () => {
    try {
      const params = {
        limit: 200,
        offset: 0,
        sortBy: sortColumn,
        sortOrder: sortDirection
      };

      if (searchTerm) params.search = searchTerm;
      if (selectedFileType !== 'all') params.fileType = selectedFileType;
      if (selectedStatus !== 'all') params.status = selectedStatus;

      const response = await getConversionRecords(params);
      setRecords(response.data?.records || []);
      setTotal(response.data?.total || 0);
    } catch (error) {
      console.error('Error loading records:', error);
      handleError(error, 'Failed to load conversion records');
    }
  };

  const loadStats = async () => {
    try {
      const response = await getConversionStats();
      setStats(response.data?.summary || null);
    } catch (error) {
      console.error('Error loading stats:', error);
      // Don't show error for stats - records are more important
    }
  };

  const handleSort = (column) => {
    if (sortColumn === column) {
      setSortDirection(prev => prev === 'asc' ? 'desc' : 'asc');
    } else {
      setSortColumn(column);
      setSortDirection('desc');
    }
  };

  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const formatDuration = (seconds) => {
    if (!seconds) return 'N/A';
    if (seconds < 60) return `${seconds.toFixed(1)}s`;
    if (seconds < 3600) return `${(seconds / 60).toFixed(1)}m`;
    return `${(seconds / 3600).toFixed(1)}h`;
  };

  const formatFileSize = (bytes) => {
    if (!bytes) return 'N/A';
    const sizes = ['B', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(1024));
    return `${(bytes / Math.pow(1024, i)).toFixed(2)} ${sizes[i]}`;
  };

  const exportToExcel = () => {
    if (records.length === 0) {
      showSuccess('No data to export');
      return;
    }

    // Use the multi-sheet export from useExportReport
    exportConversionReport(records);
    showSuccess(`Exported ${records.length} records`);
  };

  const clearFilters = () => {
    setSearchTerm('');
    setSelectedFileType('all');
    setSelectedStatus('all');
    setSortColumn('createdAt');
    setSortDirection('desc');
  };

  const getStatusColor = (status) => {
    const colors = {
      'started': 'bg-yellow-100 text-yellow-800',
      'processing': 'bg-blue-100 text-blue-800',
      'ready_for_review': 'bg-purple-100 text-purple-800',
      'editing': 'bg-orange-100 text-orange-800',
      'completed': 'bg-green-100 text-green-800',
      'failed': 'bg-red-100 text-red-800',
    };
    return colors[status] || 'bg-gray-100 text-gray-800';
  };

  const getStatusLabel = (status) => {
    const labels = {
      'started': 'Started',
      'processing': 'Processing',
      'ready_for_review': 'Ready for Review',
      'editing': 'Editing',
      'completed': 'Completed',
      'failed': 'Failed',
    };
    return labels[status] || status;
  };

  const getFileTypeBadgeColor = (fileType) => {
    const colors = {
      'epub': 'bg-purple-100 text-purple-800',
      'pdf': 'bg-red-100 text-red-800',
    };
    return colors[fileType?.toLowerCase()] || 'bg-gray-100 text-gray-800';
  };

  const statuses = ['started', 'processing', 'ready_for_review', 'editing', 'completed', 'failed'];

  const SortIcon = ({ column }) => {
    if (sortColumn !== column) return null;
    return (
      <svg className="w-4 h-4 ml-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        {sortDirection === 'asc' ? (
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
        ) : (
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        )}
      </svg>
    );
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-blue-50 to-indigo-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-4xl font-bold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent mb-2">
                Conversion Reports
              </h1>
              <p className="text-gray-600">Track and analyze all file conversions from MongoDB</p>
            </div>
            <button
              onClick={loadData}
              disabled={loading}
              className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors shadow-sm"
            >
              <svg className={`w-5 h-5 ${loading ? 'animate-spin' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
              </svg>
              Refresh
            </button>
          </div>
        </div>

        {loading ? (
          <div className="py-20">
            <Loading />
          </div>
        ) : (
          <>
            {/* Stats Cards */}
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-6">
              <div className="bg-white rounded-xl shadow-md p-4">
                <div className="text-2xl font-bold text-gray-900">{stats?.total || 0}</div>
                <div className="text-sm text-gray-500">Total Conversions</div>
              </div>
              <div className="bg-white rounded-xl shadow-md p-4">
                <div className="text-2xl font-bold text-green-600">{stats?.completed || 0}</div>
                <div className="text-sm text-gray-500">Completed</div>
              </div>
              <div className="bg-white rounded-xl shadow-md p-4">
                <div className="text-2xl font-bold text-blue-600">{stats?.processing || 0}</div>
                <div className="text-sm text-gray-500">In Progress</div>
              </div>
              <div className="bg-white rounded-xl shadow-md p-4">
                <div className="text-2xl font-bold text-red-600">{stats?.failed || 0}</div>
                <div className="text-sm text-gray-500">Failed</div>
              </div>
              <div className="bg-white rounded-xl shadow-md p-4">
                <div className="text-2xl font-bold text-red-500">{stats?.pdfCount || 0}</div>
                <div className="text-sm text-gray-500">PDF Files</div>
              </div>
              <div className="bg-white rounded-xl shadow-md p-4">
                <div className="text-2xl font-bold text-purple-600">{stats?.epubCount || 0}</div>
                <div className="text-sm text-gray-500">EPUB Files</div>
              </div>
            </div>

            {/* Additional Stats */}
            {stats && (stats.avgProcessingTime > 0 || stats.totalFileSize > 0) && (
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                <div className="bg-white rounded-xl shadow-md p-4">
                  <div className="text-xl font-bold text-indigo-600">
                    {formatDuration(stats.avgProcessingTime)}
                  </div>
                  <div className="text-sm text-gray-500">Avg Processing Time</div>
                </div>
                <div className="bg-white rounded-xl shadow-md p-4">
                  <div className="text-xl font-bold text-indigo-600">
                    {formatDuration(stats.totalProcessingTime)}
                  </div>
                  <div className="text-sm text-gray-500">Total Processing Time</div>
                </div>
                <div className="bg-white rounded-xl shadow-md p-4">
                  <div className="text-xl font-bold text-indigo-600">
                    {formatFileSize(stats.totalFileSize)}
                  </div>
                  <div className="text-sm text-gray-500">Total Data Processed</div>
                </div>
                <div className="bg-white rounded-xl shadow-md p-4">
                  <div className="text-xl font-bold text-indigo-600">
                    {formatFileSize(stats.avgFileSize)}
                  </div>
                  <div className="text-sm text-gray-500">Avg File Size</div>
                </div>
              </div>
            )}

            {/* Filters Section */}
            <div className="bg-white rounded-xl shadow-lg p-6 mb-6">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-4">
                {/* Search */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Search
                  </label>
                  <div className="relative">
                    <input
                      type="text"
                      value={searchTerm}
                      onChange={(e) => setSearchTerm(e.target.value)}
                      placeholder="Search by name, ISBN, title..."
                      className="w-full px-4 py-2 pl-10 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                    />
                    <svg className="absolute left-3 top-2.5 w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                    </svg>
                  </div>
                </div>

                {/* File Type Filter */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    File Type
                  </label>
                  <select
                    value={selectedFileType}
                    onChange={(e) => setSelectedFileType(e.target.value)}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  >
                    <option value="all">All Types</option>
                    <option value="pdf">PDF</option>
                    <option value="epub">EPUB</option>
                  </select>
                </div>

                {/* Status Filter */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Status
                  </label>
                  <select
                    value={selectedStatus}
                    onChange={(e) => setSelectedStatus(e.target.value)}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  >
                    <option value="all">All Statuses</option>
                    {statuses.map((status) => (
                      <option key={status} value={status}>
                        {getStatusLabel(status)}
                      </option>
                    ))}
                  </select>
                </div>

                {/* Action Buttons */}
                <div className="flex gap-2 items-end">
                  <button
                    onClick={clearFilters}
                    className="flex-1 px-4 py-2 bg-gray-200 text-gray-700 font-medium rounded-lg hover:bg-gray-300 transition-colors"
                  >
                    Clear
                  </button>
                  <button
                    onClick={exportToExcel}
                    disabled={records.length === 0}
                    className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white font-semibold rounded-lg hover:from-purple-700 hover:to-blue-700 transition-colors shadow-md disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Export
                  </button>
                </div>
              </div>

              {/* Stats line */}
              <div className="pt-4 border-t border-gray-200">
                <div className="flex flex-wrap items-center gap-4 text-sm text-gray-600">
                  <span>Showing <strong>{records.length}</strong> of <strong>{total}</strong> records</span>
                  {(searchTerm || selectedFileType !== 'all' || selectedStatus !== 'all') && (
                    <span className="text-xs bg-purple-100 text-purple-700 px-3 py-1 rounded-full font-medium">
                      Filters Active
                    </span>
                  )}
                </div>
              </div>
            </div>

            {/* Table */}
            <div className="bg-white rounded-xl shadow-lg overflow-hidden">
              <div className="overflow-x-auto">
                {records.length === 0 ? (
                  <div className="text-center py-16">
                    <svg className="mx-auto h-16 w-16 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    <h3 className="mt-4 text-lg font-medium text-gray-900">No Conversion Records</h3>
                    <p className="mt-2 text-sm text-gray-500">
                      {total === 0
                        ? 'No files have been processed yet. Conversion tracking starts when files are uploaded.'
                        : 'Try adjusting your filters.'}
                    </p>
                  </div>
                ) : (
                  <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gradient-to-r from-purple-600 to-blue-600 sticky top-0 z-10">
                      <tr>
                        <th
                          className="px-6 py-3 text-left text-xs font-bold text-white uppercase tracking-wider cursor-pointer hover:bg-purple-700"
                          onClick={() => handleSort('fileName')}
                        >
                          <div className="flex items-center">
                            File Name
                            <SortIcon column="fileName" />
                          </div>
                        </th>
                        <th className="px-6 py-3 text-left text-xs font-bold text-white uppercase tracking-wider">
                          Type
                        </th>
                        <th
                          className="px-6 py-3 text-left text-xs font-bold text-white uppercase tracking-wider cursor-pointer hover:bg-purple-700"
                          onClick={() => handleSort('status')}
                        >
                          <div className="flex items-center">
                            Status
                            <SortIcon column="status" />
                          </div>
                        </th>
                        <th className="px-6 py-3 text-left text-xs font-bold text-white uppercase tracking-wider">
                          Size
                        </th>
                        <th className="px-6 py-3 text-left text-xs font-bold text-white uppercase tracking-wider">
                          User
                        </th>
                        <th
                          className="px-6 py-3 text-left text-xs font-bold text-white uppercase tracking-wider cursor-pointer hover:bg-purple-700"
                          onClick={() => handleSort('startedAt')}
                        >
                          <div className="flex items-center">
                            Started
                            <SortIcon column="startedAt" />
                          </div>
                        </th>
                        <th
                          className="px-6 py-3 text-left text-xs font-bold text-white uppercase tracking-wider cursor-pointer hover:bg-purple-700"
                          onClick={() => handleSort('processingDurationSeconds')}
                        >
                          <div className="flex items-center">
                            Duration
                            <SortIcon column="processingDurationSeconds" />
                          </div>
                        </th>
                        <th className="px-6 py-3 text-left text-xs font-bold text-white uppercase tracking-wider">
                          Outputs
                        </th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {records.map((record) => (
                        <tr key={record._id} className="hover:bg-gray-50 transition-colors">
                          <td className="px-6 py-4 text-sm">
                            <div className="font-medium text-gray-900 max-w-xs truncate" title={record.fileName}>
                              {record.fileName}
                            </div>
                            {record.isbn && (
                              <div className="text-xs text-gray-500">ISBN: {record.isbn}</div>
                            )}
                            {record.title && (
                              <div className="text-xs text-gray-400 truncate" title={record.title}>
                                {record.title}
                              </div>
                            )}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap">
                            <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getFileTypeBadgeColor(record.fileType)}`}>
                              {record.fileType?.toUpperCase()}
                            </span>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap">
                            <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusColor(record.status)}`}>
                              {getStatusLabel(record.status)}
                            </span>
                            {record.status === 'failed' && record.errorMessage && (
                              <div className="text-xs text-red-500 mt-1 max-w-xs truncate" title={record.errorMessage}>
                                {record.errorMessage}
                              </div>
                            )}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                            {formatFileSize(record.fileSize)}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                            {record.uploadedByUsername || record.uploadedBy?.username || 'Unknown'}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                            {formatDate(record.startedAt)}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                            {formatDuration(record.processingDurationSeconds)}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                            {record.outputCount || 0} file(s)
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                )}
              </div>

              {/* Pagination Info */}
              {records.length > 0 && (
                <div className="bg-gray-50 px-6 py-4 border-t border-gray-200">
                  <p className="text-sm text-gray-600 text-center">
                    Showing {records.length} of {total} conversion records
                  </p>
                </div>
              )}
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default ConversionDashboard;
